trigger:
  batch: true
  branches:
    include:
    - master
    - develop
  paths:
    include:
    - 'DryWetMidi/*'
    - 'Resources/CI/build-artifacts-library.yaml'

pr: none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  version: '5.2.0'

name: $(TeamProject)_$(SourceBranchName)_BuildLibrary_$(version)$(Rev:.r)

steps:
- task: PowerShell@2
  displayName: Generate obsolete API hints
  inputs:
    targetType: filePath
    filePath: '$(Build.SourcesDirectory)/Resources/Scripts/Generate obsolete API hints.ps1'

- task: DotNetCoreCLI@2
  displayName: Build solution
  inputs:
    command: 'build'
    projects: |
      DryWetMidi/Melanchall.DryWetMidi.csproj
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Create NuGet package
  inputs: 
    command: 'pack'
    projects: 'DryWetMidi/Melanchall.DryWetMidi.csproj'
    outputDir: '$(Build.ArtifactStagingDirectory)\NuGetPackage'
    packagesToPack: 'DryWetMidi/Melanchall.DryWetMidi.csproj'
    nobuild: true

- task: PublishPipelineArtifact@1
  displayName: Publish 'NuGetPackage' artifact
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)\NuGetPackage'
    artifact: NuGetPackage

- task: PowerShell@2
  displayName: Delete pdb files
  inputs:
    targetType: 'inline'
    script: |
      Get-ChildItem $(Build.SourcesDirectory) -Include *.pdb -Recurse | Remove-Item -Force

- task: ArchiveFiles@2
  displayName: Archive .NET Framework binaries
  inputs:
    rootFolderOrFile: 'DryWetMidi\bin\$(buildConfiguration)\net45'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)\Binaries\DryWetMIDI.$(version)-bin-net45.zip'

- task: ArchiveFiles@2
  displayName: Archive .NET Standard binaries
  inputs:
    rootFolderOrFile: 'DryWetMidi\bin\$(buildConfiguration)\netstandard2.0'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)\Binaries\DryWetMIDI.$(version)-bin-netstandard20.zip'

- task: PublishPipelineArtifact@1
  displayName: Publish 'Binaries' artifact
  inputs:
    targetPath: $(Build.ArtifactStagingDirectory)\Binaries
    artifact: Binaries