trigger:
  branches:
    include:
    - master
    - develop
  paths:
    include:
    - 'Docs/*'
    - 'Resources/Scripts/Check links.ps1'
    - 'Resources/CI/check-docs-links.yaml'

pr:
  branches:
    include:
    - develop
  paths:
    include:
    - 'Docs/*'
    - 'Resources/Scripts/Check links.ps1'
    - 'Resources/CI/check-docs-links.yaml'

schedules:
- cron: '0 0,9,15,20 * * *'
  displayName: Check docs links schedule
  branches:
    include:
    - master
    - develop
  always: 'true'

pool:
  vmImage: 'windows-latest'

name: $(TeamProject)_$(SourceBranchName)_CheckDocsLinks_$(Rev:r)

steps:
- task: PowerShell@2
  displayName: Check links
  inputs:
    targetType: filePath
    filePath: '$(Build.SourcesDirectory)/Resources/Scripts/Check links.ps1'
    arguments: '-Folder "$(Build.SourcesDirectory)/Docs" -Filter "*.md"'
    failOnStderr: 'true'