trigger:
  batch: true
  branches:
    include:
    - master
    - develop
  paths:
    include:
    - 'DryWetMidi/*'
    - 'DryWetMidi.Tests/*'
    - 'DryWetMidi.Tests.Common/*'
    - 'Resources/CI/mac-test-netcore-core.yaml'
    exclude:
    - 'DryWetMidi/Devices/*'
    - 'DryWetMidi.Tests/Devices/*'

pr:
  branches:
    include:
    - develop
  paths:
    include:
    - 'DryWetMidi/*'
    - 'DryWetMidi.Tests/*'
    - 'DryWetMidi.Tests.Common/*'
    - 'Resources/CI/mac-test-netcore-core.yaml'
    exclude:
    - 'DryWetMidi/Devices/*'
    - 'DryWetMidi.Tests/Devices/*'

pool:
  vmImage: 'macOS-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  version: '5.2.0'

name: macOS_Test_NetCore_Core_$(version)$(Rev:.r)

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core 2.1'
  inputs:
    packageType: sdk
    version: 2.1.804
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: Build DryWetMidi and DryWetMidi.Tests.Common
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration) --framework netstandard2.0'
    projects: |
      DryWetMidi/Melanchall.DryWetMidi.csproj
      DryWetMidi.Tests.Common/Melanchall.DryWetMidi.Tests.Common.csproj

- task: DotNetCoreCLI@2
  displayName: Build DryWetMidi.Tests
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration) --framework netcoreapp2.1'
    projects: |
      DryWetMidi.Tests/Melanchall.DryWetMidi.Tests.csproj

- task: DotNetCoreCLI@2
  displayName: Run unit tests
  continueOnError: true
  inputs:
    command: 'test'
    projects: 'DryWetMidi.Tests/Melanchall.DryWetMidi.Tests.csproj'
    arguments: '--blame --no-build --configuration $(buildConfiguration) --filter ((FullyQualifiedName~Melanchall.DryWetMidi.Tests.Core|FullyQualifiedName~Melanchall.DryWetMidi.Tests.Common|FullyQualifiedName~Melanchall.DryWetMidi.Tests.Composing|FullyQualifiedName~Melanchall.DryWetMidi.Tests.Interaction|FullyQualifiedName~Melanchall.DryWetMidi.Tests.MusicTheory|FullyQualifiedName~Melanchall.DryWetMidi.Tests.Standards|FullyQualifiedName~Melanchall.DryWetMidi.Tests.Tools)&Name!=CheckValidFilesReadingByReferences) --framework netcoreapp2.1 --verbosity normal'
