trigger:
  batch: true
  branches:
    include:
    - master
    - develop
  paths:
    include:
    - 'Resources/Utilities/ExportNuGetStatistics/*'
    - 'Resources/CI/stat-nuget.yaml'

pr: none

schedules:
- cron: '0 0 * * *'
  displayName: Export NuGet package statistics
  branches:
    include:
    - develop
  always: 'true'

pool:
  vmImage: 'windows-latest'

name: $(TeamProject)_ExportNuGetStat_$(Rev:r)

steps:
- task: PowerShell@2
  displayName: Export NuGet package info to InfluxDB Cloud
  inputs:
    targetType: 'inline'
    script: |
      $location = Get-Location
      Write-Host "Building ExportNuGetStatistics..."
      dotnet publish "Resources/Utilities/ExportNuGetStatistics/ExportNuGetStatistics.sln" -c Release -r win10-x64 -o "$location/ExportNuGetStatistics"
      Write-Host "Built."
      
      Write-Host "Exporting NuGet package info..."
      $url = "$(InfluxCloudUrl)"
      $token = "$(InfluxCloudToken)"
      $organization = "$(InfluxCloudOrganization)"
      $bucket = "$(InfluxCloudBucket)"
      $measurement = "$(InfluxCloudMeasurement)"
      Start-Process "ExportNuGetStatistics/ExportNuGetStatistics.exe" -ArgumentList """$url"" ""$token"" ""$organization"" ""$bucket"" ""$measurement""" -Wait -NoNewWindow
      Write-Host "Exported."