trigger:
  batch: true
  branches:
    include:
    - master
    - develop
  paths:
    include:
    - 'DryWetMidi/*'
    - 'DryWetMidi.Tests/*'
    - 'DryWetMidi.Tests.Common/*'
    - 'Resources/CI/win-test-netcore-devices.yaml'
    - 'Resources/Utilities/CreateLoopbackPort/*'
    - 'Resources/Scripts/Setup MIDI ports.ps1'

pr:
  branches:
    include:
    - develop
  paths:
    include:
    - 'DryWetMidi/*'
    - 'DryWetMidi.Tests/*'
    - 'DryWetMidi.Tests.Common/*'
    - 'Resources/CI/win-test-netcore-devices.yaml'
    - 'Resources/Utilities/CreateLoopbackPort/*'
    - 'Resources/Scripts/Setup MIDI ports.ps1'

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  version: '5.2.0'

name: Windows_Test_NetCore_Devices_$(version)$(Rev:.r)

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core 2.1'
  inputs:
    packageType: sdk
    version: 2.1.804
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: Build DryWetMidi and DryWetMidi.Tests.Common
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration) --framework netstandard2.0'
    projects: |
      DryWetMidi/Melanchall.DryWetMidi.csproj
      DryWetMidi.Tests.Common/Melanchall.DryWetMidi.Tests.Common.csproj

- task: DotNetCoreCLI@2
  displayName: Build DryWetMidi.Tests
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration) --framework netcoreapp2.1'
    projects: |
      DryWetMidi.Tests/Melanchall.DryWetMidi.Tests.csproj

- task: PowerShell@2
  displayName: Setup MIDI ports for devices API tests
  inputs:
    targetType: filePath
    filePath: '$(Build.SourcesDirectory)/Resources/Scripts/Setup MIDI ports.ps1'

- task: DotNetCoreCLI@2
  displayName: Run unit tests
  continueOnError: true
  inputs:
    command: 'test'
    projects: 'DryWetMidi.Tests/Melanchall.DryWetMidi.Tests.csproj'
    arguments: '--blame --no-build --configuration $(buildConfiguration) --filter (FullyQualifiedName~.Devices) --framework netcoreapp2.1 --verbosity normal'
