trigger:
  batch: true
  branches:
    include:
    - master
    - develop
  paths:
    include:
    - 'DryWetMidi/*'
    - 'DryWetMidi.Tests/*'
    - 'DryWetMidi.Tests.Common/*'
    - 'Resources/CI/win-test-netframework-devices.yaml'
    - 'Resources/Utilities/CreateLoopbackPort/*'
    - 'Resources/Scripts/Setup MIDI ports.ps1'

pr:
  branches:
    include:
    - develop
  paths:
    include:
    - 'DryWetMidi/*'
    - 'DryWetMidi.Tests/*'
    - 'DryWetMidi.Tests.Common/*'
    - 'Resources/CI/win-test-netframework-devices.yaml'
    - 'Resources/Utilities/CreateLoopbackPort/*'
    - 'Resources/Scripts/Setup MIDI ports.ps1'

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  version: '5.2.0'

name: Windows_Test_NetFramework_Devices_$(version)$(Rev:.r)

steps:
- task: NugetToolInstaller@1
  displayName: Install latest NuGet tool

- task: DotNetCoreCLI@2
  displayName: Restore NuGet packages
  inputs:
    command: restore

- task: DotNetCoreCLI@2
  displayName: Build solution
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'

- task: PowerShell@2
  displayName: Setup MIDI ports for devices API tests
  inputs:
    targetType: filePath
    filePath: '$(Build.SourcesDirectory)/Resources/Scripts/Setup MIDI ports.ps1'

- task: VSTest@2
  displayName: Run unit tests
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    testSelector: testAssemblies
    testAssemblyVer2:
      '**/*.Tests.dll'
    testFiltercriteria: 'FullyQualifiedName~.Devices'
    rerunMaxAttempts: '3'
